name: mne2_arm
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - _r-mutex=1.0.1=anacondar_1
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.0=py312h8acbcb3_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - antio=0.6.1=py312h84eede6_0
  - anyio=4.11.0=pyhcf101f3_0
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py312h4409184_1
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blosc=1.21.6=h7dd00d9_1
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - brotli-python=1.1.0=py312h6b01ec3_4
  - brunsli=0.1=h97083b6_1
  - bwidget=1.10.1=hce30654_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - c-blosc2=2.21.3=hb5916c8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h6a3b0d2_0
  - cctools_osx-arm64=1024.3=llvm21_1_haddd2d4_5
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py312hb65edc0_0
  - charls=2.4.2=h13dd4ca_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - clang=21.1.3=default_hf9bcbb7_0
  - clang-21=21.1.3=default_h489deba_0
  - clang_impl_osx-arm64=21.1.3=h3492924_25
  - clang_osx-arm64=21.1.3=h07b0088_25
  - clangxx=21.1.3=default_h36137df_0
  - clangxx_impl_osx-arm64=21.1.3=h03b555f_25
  - clangxx_osx-arm64=21.1.3=h07b0088_25
  - cli11=2.5.0=ha1acc90_0
  - click=8.3.0=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - compiler-rt=21.1.3=hce30654_0
  - compiler-rt21=21.1.3=h855ad52_0
  - compiler-rt21_osx-arm64=21.1.3=h2514db7_0
  - contourpy=1.3.3=py312ha0dd364_2
  - cpython=3.12.12=py312hd8ed1ab_0
  - curl=8.14.1=h73640d1_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - darkdetect=0.8.0=pyhd8ed1ab_1
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.16.2=hda038a8_0
  - debugpy=1.8.17=py312h56d30c9_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - deepdiff=8.6.1=pyhcf101f3_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - dipy=1.11.0=np2py312h8216225_1
  - double-conversion=3.3.1=h286801f_0
  - edfio=0.4.10=pyhd8ed1ab_0
  - eeglabio=0.1.2=pyhd8ed1ab_0
  - eigen=3.4.0=h49c215f_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=hec049ff_0
  - ffmpeg=8.0.0=gpl_h670d5b4_106
  - fmt=11.2.0=h440487c_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py312h5748b74_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - frozenlist=1.7.0=py312h512c567_0
  - gdk-pixbuf=2.44.3=h7542897_0
  - gfortran_impl_osx-arm64=14.3.0=h6d03799_1
  - gfortran_osx-arm64=14.3.0=h3c33bd0_0
  - giflib=5.2.2=h93a5062_0
  - glib=2.86.0=h52a91e1_0
  - glib-tools=2.86.0=hb9d6e3a_0
  - glslang=16.0.0=h60b4770_0
  - gmp=6.3.0=h7bae524_2
  - graphite2=1.3.14=hec049ff_2
  - gsl=2.7=h6e638da_0
  - gst-plugins-base=1.24.11=h3c5c1d0_0
  - gstreamer=1.24.11=hfe24232_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - h5io=0.2.5=pyhecae5ae_0
  - h5py=3.15.1=nompi_py312h4eecd6b_100
  - harfbuzz=12.1.0=haf38c7b_0
  - hdf4=4.2.15=h2ee6834_7
  - hdf5=1.14.6=nompi_he65715a_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - imagecodecs=2025.8.2=py312h8d74250_4
  - imageio=2.37.0=pyhfb79c49_0
  - imageio-ffmpeg=0.6.0=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=7.0.1=pyh5552912_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isl=0.26=imath32_h347afa1_101
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsoncpp=1.9.6=h726d253_1
  - jsonpointer=3.0.0=py312h81bd7bf_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.9=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - jxrlib=1.1=h93a5062_3
  - kiwisolver=1.4.9=py312hdc12c9d_1
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lark=1.3.0=pyhd8ed1ab_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h7eeda09_0
  - ld64=955.13=h5d6df6c_5
  - ld64_osx-arm64=955.13=llvm21_1_hde6573c_5
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libaec=1.1.4=h51d1e36_0
  - libasprintf=0.25.1=h493aca8_0
  - libass=0.17.4=hcbd7ca7_0
  - libavif16=1.3.0=hb06b76e_2
  - libblas=3.9.0=37_h51639a9_openblas
  - libboost=1.88.0=h18cd856_5
  - libboost-devel=1.88.0=hf450f58_5
  - libboost-headers=1.88.0=hce30654_5
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=37_hb0561ab_openblas
  - libclang-cpp18.1=18.1.8=default_h73dfc95_15
  - libclang-cpp19.1=19.1.7=default_h73dfc95_5
  - libclang-cpp21.1=21.1.3=default_h73dfc95_0
  - libclang13=21.1.3=default_h6e8f826_0
  - libcurl=8.14.1=h73640d1_0
  - libcxx=21.1.3=hf598326_0
  - libcxx-devel=21.1.3=h6dc3340_0
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgettextpo=0.25.1=h493aca8_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran-devel_osx-arm64=14.3.0=hc965647_1
  - libgfortran5=15.2.0=h742603c_1
  - libglib=2.86.0=h1bb475b_0
  - libhwloc=2.12.1=default_h48b22c3_1002
  - libhwy=1.3.0=h48b13b8_1
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - libjxl=0.11.1=h7274d02_4
  - liblapack=3.9.0=37_hd9741b5_openblas
  - libllvm18=18.1.8=default_h3f38c9c_10
  - libllvm19=19.1.7=h8e0c9ce_2
  - libllvm21=21.1.3=h8e0c9ce_0
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libmatio=1.5.28=h54e7284_3
  - libnetcdf=4.9.3=nompi_h80c4520_103
  - libnghttp2=1.67.0=hc438710_0
  - libntlm=1.8=h5505292_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=openmp_ha158390_2
  - libopenvino=2025.2.0=h56e7ac4_1
  - libopenvino-arm-cpu-plugin=2025.2.0=h56e7ac4_1
  - libopenvino-auto-batch-plugin=2025.2.0=he81eb65_1
  - libopenvino-auto-plugin=2025.2.0=he81eb65_1
  - libopenvino-hetero-plugin=2025.2.0=h273c05f_1
  - libopenvino-ir-frontend=2025.2.0=h273c05f_1
  - libopenvino-onnx-frontend=2025.2.0=h6386500_1
  - libopenvino-paddle-frontend=2025.2.0=h6386500_1
  - libopenvino-pytorch-frontend=2025.2.0=hec049ff_1
  - libopenvino-tensorflow-frontend=2025.2.0=hee62d61_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hec049ff_1
  - libopus=1.5.2=h48c0fde_0
  - libpng=1.6.50=h280e0eb_1
  - libpq=18.0=h31f7a3a_0
  - libprotobuf=6.31.1=h658db43_2
  - librsvg=2.60.0=h5c55ec3_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.4=h4237e3c_0
  - libssh2=1.11.1=h1590b86_0
  - libtheora=1.1.1=h99b78c6_1006
  - libtiff=4.7.1=h7dc4979_0
  - libusb=1.0.29=hbc156a2_0
  - libvorbis=1.3.7=h81086ad_2
  - libvpx=1.14.1=h7bae524_0
  - libvulkan-loader=1.4.328.1=h49c215f_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.0=h9329255_1
  - libxml2-16=2.15.0=h0ff4647_1
  - libxslt=1.1.43=hb2570ba_1
  - libzip=1.11.2=h1336266_0
  - libzlib=1.3.1=h8359307_2
  - libzopfli=1.0.3=h9f76cd9_0
  - llvm-openmp=21.1.3=h4a912ad_0
  - llvm-tools=21.1.3=h855ad52_0
  - llvm-tools-21=21.1.3=h91fd4e7_0
  - llvmlite=0.45.1=py312hc82e5dd_0
  - loguru=0.7.3=pyh707e725_0
  - lxml=6.0.2=py312h447b5cf_1
  - lz4-c=1.10.0=h286801f_1
  - make=4.4.1=hc9fafa5_2
  - markupsafe=3.0.3=py312h5748b74_0
  - matplotlib=3.10.7=py312h1f38498_0
  - matplotlib-base=3.10.7=py312h605b88b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mffpy=0.10.0=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - mne=1.10.2=osx_pyqt_h8d421b4_200
  - mne-base=1.10.2=pyh694c41f_200
  - mne-bids=0.17.0=pyhd8ed1ab_0
  - mne-qt-browser=0.7.3=pyh0555025_0
  - more-itertools=10.8.0=pyhd8ed1ab_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - msgpack-python=1.1.2=py312h84eede6_0
  - multidict=6.6.3=py312hdb8e49c_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - nibabel=5.3.2=pyha770c72_1
  - nilearn=0.12.1=pyhd8ed1ab_0
  - nlohmann_json=3.12.0=h248ca61_1
  - notebook=7.4.7=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - nspr=4.37=h31e89c2_0
  - nss=3.117=h1c710a3_0
  - numba=0.62.1=py312hd24c766_0
  - numexpr=2.14.1=py312h3de7d89_0
  - numpy=2.3.3=py312h85ea64e_0
  - openh264=2.6.0=hb5b2745_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openldap=2.6.10=hbe55e7a_0
  - openmeeg=2.5.15=py312h0217555_2
  - openssl=3.5.4=h5503f6c_0
  - orderly-set=5.5.0=pyhe01879c_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312h5978115_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.4=h875632e_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.46=h7125dd6_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py312h2525f64_3
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - ply=3.11=pyhd8ed1ab_3
  - pooch=1.8.2=pyhd8ed1ab_3
  - proj=9.7.0=hf83150c_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - propcache=0.3.1=py312h998013c_0
  - psutil=7.1.0=py312h4409184_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=hd3d436d_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pybv=0.7.6=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pymatreader=1.1.0=pyhd8ed1ab_0
  - pyobjc-core=11.1=py312h4c66426_1
  - pyobjc-framework-cocoa=11.1=py312h3964663_1
  - pyopengl=3.1.10=pyh534df25_2
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyqt=5.15.11=py312h6612b97_2
  - pyqt5-sip=12.17.0=py312h455b684_2
  - pyqtgraph=0.13.7=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - pytables=3.10.2=py312hc3f5fac_9
  - python=3.12.12=hec0b533_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.12=hd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-picard=0.8=pyha308f57_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyvista=0.46.3=pyhd8ed1ab_1
  - pyvistaqt=0.11.3=pyhdecd6ff_0
  - pywavelets=1.9.0=py312hc7121bb_1
  - pyyaml=6.0.3=py312h5748b74_0
  - pyzmq=27.1.0=py312hd65ceae_0
  - qdarkstyle=3.2.3=pyhd8ed1ab_1
  - qhull=2020.2=h420ef59_5
  - qt-main=5.15.15=h9b65787_6
  - qt6-main=6.9.3=hb266e41_0
  - qtpy=2.4.3=pyhd8ed1ab_1
  - r-base=4.4.3=hb7b3c91_4
  - r-bayesfactor=0.9.12_4.7=r44hc1cd577_2
  - r-cli=3.6.5=r44hc1cd577_1
  - r-coda=0.19_4.1=r44hc72bb7e_2
  - r-contfrac=1.1_12=r44h6168396_1007
  - r-desolve=1.40=r44hb2d3ebe_2
  - r-elliptic=1.5_0=r44hc72bb7e_0
  - r-glue=1.8.0=r44h6168396_1
  - r-gtools=3.9.5=r44h6168396_2
  - r-hypergeo=1.2_14=r44hc72bb7e_1
  - r-lattice=0.22_7=r44h6168396_1
  - r-lifecycle=1.0.4=r44hc72bb7e_2
  - r-magrittr=2.0.4=r44h6168396_0
  - r-mass=7.3_65=r44h6168396_0
  - r-matrix=1.7_4=r44hb2d3ebe_1
  - r-matrixmodels=0.5_4=r44hc72bb7e_1
  - r-mvtnorm=1.3_3=r44hb2d3ebe_1
  - r-pbapply=1.7_4=r44hc72bb7e_1
  - r-rcpp=1.1.0=r44hc1cd577_1
  - r-rcppeigen=0.3.4.0.2=r44hd057375_1
  - r-rlang=1.1.6=r44hc1cd577_1
  - r-stringi=1.8.7=r44he9eb878_1
  - r-stringr=1.5.2=r44h785f33e_1
  - r-vctrs=0.6.5=r44hc1cd577_2
  - rav1e=0.7.1=h0716509_3
  - readline=8.2=h1d1bf99_2
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.27.1=py312h6f58b40_1
  - rpy2=3.6.4=py312r44hd99f0fb_1
  - scikit-image=0.25.2=py312h5978115_2
  - scikit-learn=1.7.2=py312h79e0ffc_0
  - scipy=1.16.2=py312ha6bbf71_0
  - scooby=0.10.2=pyhd8ed1ab_0
  - sdl2=2.32.56=h248ca61_0
  - sdl3=3.2.24=h919df07_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=80.9.0=pyhff2d567_0
  - setuptools-scm=9.2.1=pyhd8ed1ab_0
  - shaderc=2025.4=h1a5098f_0
  - sigtool=0.1.3=h44b9a77_0
  - sip=6.13.1=py312h455b684_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hd121638_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - spirv-tools=2025.4=ha7d2532_0
  - sqlite=3.50.4=hb5dd463_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py312ha11c99a_1
  - svt-av1=3.1.2=h12ba402_0
  - tapi=1300.6.5=h03f4b80_0
  - tbb=2022.2.0=h5b2e6d4_1
  - tbb-devel=2022.2.0=h89693d0_1
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2025.10.16=pyhd8ed1ab_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h892fb3f_2
  - tktable=2.10=h3c7de25_7
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.2=py312h163523d_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - trame=3.12.0=pyhd8ed1ab_0
  - trame-client=3.11.2=pyhd8ed1ab_0
  - trame-common=1.0.1=pyhd8ed1ab_0
  - trame-server=3.6.3=pyhd8ed1ab_0
  - trame-vtk=2.10.0=pyhfc31425_0
  - trame-vuetify=3.1.0=pyhd8ed1ab_0
  - trx-python=0.3=py312h81bd7bf_1
  - types-python-dateutil=2.9.0.20251008=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - tzlocal=5.3.1=pyh8f84b5b_0
  - unicodedata2=16.0.0=py312h163523d_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - utfcpp=4.0.8=hce30654_0
  - vtk=9.5.2=had17e93_0
  - vtk-base=9.5.2=py312he37cbfc_0
  - vtk-io-ffmpeg=9.5.2=h13a62d8_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - wrapt=1.17.3=py312h163523d_1
  - wslink=2.4.0=pyhd8ed1ab_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xlrd=2.0.2=pyhd8ed1ab_0
  - xmltodict=1.0.2=pyhcf101f3_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.20.1=py312h998013c_0
  - zeromq=4.3.5=h888dc83_9
  - zfp=1.0.1=hfd287c0_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.2.5=hf787086_0
  - zstandard=0.25.0=py312h37e1c23_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - args==0.1.0
      - clint==0.5.1
      - coverage==7.11.0
      - dill==0.4.0
      - et-xmlfile==2.0.0
      - iniconfig==2.1.0
      - ipympl==0.9.8
      - openpyxl==3.1.5
      - pluggy==1.6.0
      - pysimplegui==5.0.8.3
      - pytest==8.4.2
      - rpy2-rinterface==3.6.3
      - rpy2-robjects==3.6.3
      - wget==3.2
prefix: /opt/miniconda3/envs/mne2_arm
